### ISSUE TITLE
module 'gitbatch.utils.copy' has no attribute 'simplecopytree'

### ISSUE THREAD

**Issue by nirajacharya2** [thegeeklab/git-batch#564]
There is a bug in the latest build of git-batch. introduced in https://github.com/thegeeklab/git-batch/pull/563

```shell
+ git-batch -vv

Traceback (most recent call last):
  File "/usr/local/bin/git-batch", line 7, in <module>
    sys.exit(main())
             ~~~~^^
  File "/usr/local/lib/python3.14/site-packages/gitbatch/cli.py", line 172, in main
    GitBatch()
    ~~~~~~~~^^
  File "/usr/local/lib/python3.14/site-packages/gitbatch/cli.py", line 27, in __init__
    self.run()
    ~~~~~~~~^^
  File "/usr/local/lib/python3.14/site-packages/gitbatch/cli.py", line 162, in run
    self._repos_clone(repos)
    ~~~~~~~~~~~~~~~~~^^^^^^^
  File "/usr/local/lib/python3.14/site-packages/gitbatch/cli.py", line 133, in _repos_clone
    copy.simplecopytree(
    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'gitbatch.utils.copy' has no attribute 'simplecopytree'. Did you mean: 'simple_copytree'?
```

https://drone.owncloud.com/owncloud/owncloud.github.io/28968/1/4
